// <auto-generated />
using System;
using FrippesFlow.data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FrippesFlow.Migrations
{
    [DbContext(typeof(FrippesFlowContext))]
    [Migration("20241007113451_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("FrippesFlow.Models.SalesEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AmountSold")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PricePer")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Week")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SalesEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
